import json

categories = {
    "Dating": ["pof", "tinder", "bumble", "hinge", "match", "okcupid", "badoo", "happn", "coffeemeetsbagel", "ashleymadison", "asiandating", "blackpeoplemeet", "christianmingle", "eharmony", "farmersonly", "jdate", "ourtime", "zoosk", "feeld", "grindr", "her", "scruff", "jackd", "chispa", "hily", "lovoo", "mamba", "meetme", "skout", "tagged", "wink", "yubo", "boo", "dilmil", "muzmatch", "shaadi", "jeevansathi", "catholicmatch", "jswipe", "singleparentmeet", "seniorpeoplemeet", "blackpeoplemeet", "latinopeoplemeet", "datemyage", "silversingles", "elitesingles", "seeking", "secretbenefits", "sugardaddy", "sugardaddymeet", "sugarbook", "mysugardaddy", "whatsyourprice", "millionairematch", "luxy", "raya", "theinner circle", "theleague", "hud", "pure", "casualx", "down", "feeld", "3fun", "fetlife", "fetish", "adultfriendfinder", "alt", "bdsm", "collarspace", "kinkd", "whiplr", "brazilcupid", "colombiancupid", "filipinocupid", "mexicancupid", "thaicupid", "vietnamcupid", "internationalcupid", "caribbeancupid", "africanlove", "asiandate", "latinamericancupid", "russiancupid", "ukrainedate", "chinalovecupid", "japancupid", "koreancupid", "2redbeans", "baihe", "jiayuan", "tantan", "momo", "blued", "aloha", "paktor", "loveisland", "marriagemindedpeoplemeet", "chemistry", "positivesingles", "herpesdatingsite", "hivdatingsites", "stdmatch", "mpwh", "hsv singles", "hdate", "hmates", "bigolive", "bigbeautifulpeople", "wooplus", "largefriends", "bbwcupid", "bbwromance", "feabie", "curvesconnect", "chubbydate"],
    
    "Social": ["facebook", "instagram", "twitter", "x", "snapchat", "tiktok", "discord", "reddit", "linkedin", "pinterest", "tumblr", "vk", "weibo", "wechat", "line", "kakaotalk", "viber", "telegram", "whatsapp", "signal", "threema", "wickr", "kik", "groupme", "skype", "zoom", "teams", "slack", "clubhouse", "parler", "gab", "truthsocial", "gettr", "rumble", "minds", "mewe", "nextdoor", "meetup", "yubo", "houseparty", "bunch", "marco polo", "locket", "poparazzi", "dispo", "bereal", "threads", "bluesky", "mastodon", "noplace", "yikyak", "fizz", "sidechat", "clapper", "triller", "likee", "kwai", "helo", "josh", "moj", "chingari", "roposo", "sharechat", "mx takatak", "snack video", "zili", "firework", "clash", "byte", "dubsmash", "funimate", "lomotif", "vigo video", "bigo live", "uplive", "liveme", "streamkar", "nonolive", "mico", "yalla", "hago", "tango", "azar", "chamet", "lamour", "wink", "yubo", "monkey", "holla", "omega", "ome.tv", "chatroulette", "camsurf", "chatspin", "shagle", "faceflow", "tinychat", "paltalk", "camfrog", "stickam", "ustream", "livestream", "periscope", "meerkat", "blab", "busker", "younow", "live.ly", "musical.ly", "dubsmash"],
    
    "Messaging": ["whatsapp", "telegram", "signal", "messenger", "imessage", "wechat", "line", "viber", "kakaotalk", "skype", "discord", "slack", "teams", "zoom", "google chat", "hangouts", "allo", "duo", "facetime", "snapchat", "instagram", "twitter", "facebook", "kik", "groupme", "wickr", "threema", "wire", "element", "matrix", "session", "briar", "jami", "tox", "ricochet", "cwtch", "bitmessage", "retroshare", "i2p-bote", "surespot", "cryptocat", "silent phone", "silent text", "redphone", "textsecure", "chatsecure", "conversations", "xabber", "gajim", "pidgin", "adium", "trillian", "miranda", "digsby", "meebo", "aim", "icq", "yahoo messenger", "msn messenger", "windows live messenger", "google talk", "jabber", "xmpp", "irc", "mattermost", "rocket.chat", "zulip", "riot", "gitter", "flock", "twist", "chanty", "pumble", "spike", "front", "hiver", "missive", "polymail", "superhuman", "hey", "protonmail", "tutanota", "mailfence", "posteo", "runbox", "kolab now", "mailbox.org", "fastmail", "zoho mail", "yandex mail", "gmx", "mail.com", "aol mail", "outlook", "yahoo mail", "gmail", "icloud mail"],
    
    "Finance": ["cashapp", "venmo", "paypal", "zelle", "chime", "current", "varo", "dave", "earnin", "brigit", "moneylion", "albert", "cleo", "possible", "empower", "floatme", "grid", "klover", "solo", "branch", "even", "payactiv", "dailypay", "instant", "rain", "tapcheck", "wisely", "netspend", "greendot", "bluebird", "serve", "gobank", "simple", "n26", "revolut", "monzo", "starling", "tandem", "atom", "monese", "bunq", "curve", "transferwise", "wise", "remitly", "worldremit", "xoom", "azimo", "instarem", "ofx", "currencyfair", "xe", "moneygram", "westernunion", "ria", "transfast", "small world", "xendpay", "sendwave", "wave", "chipper", "flutterwave", "paystack", "stripe", "square", "braintree", "adyen", "checkout", "mollie", "klarna", "afterpay", "affirm", "sezzle", "quadpay", "splitit", "laybuy", "clearpay", "zip", "openpay", "humm", "latitude", "certegy", "flexiti", "paybright", "fairstone", "goeasy", "mogo", "borrowell", "credit karma", "nerdwallet", "mint", "ynab", "pocketguard", "goodbudget", "everydollar", "honeydue", "spendee", "wally", "toshl", "monefy", "expense iq", "spending tracker", "money lover", "wallet", "money manager", "andromoney", "bluecoins", "financisto", "my money", "money pro", "banktivity", "moneydance", "quicken", "quickbooks", "freshbooks", "wave", "xero", "zoho books", "kashoo", "billy", "zipbooks", "invoice ninja", "invoicely", "invoice2go", "square invoices", "paypal invoicing", "stripe invoicing", "coinbase", "binance", "kraken", "gemini", "bitstamp", "bitfinex", "bittrex", "poloniex", "huobi", "okex", "kucoin", "gate.io", "crypto.com", "ftx", "bybit", "deribit", "bitmex", "phemex", "primexbt", "bitget", "mexc", "ascendex", "probit", "lbank", "bitmart", "hotbit", "xt.com", "digifinex", "coinsbit", "exmo", "cex.io", "coinmama", "coinbase", "robinhood", "webull", "etrade", "tdameritrade", "schwab", "fidelity", "vanguard", "merrill", "ally", "sofi", "m1finance", "acorns", "stash", "betterment", "wealthfront", "ellevest", "blooom", "wealthsimple", "questrade", "interactive brokers", "tastyworks", "tradestation", "lightspeed", "speedtrader", "centerpoint", "suretrader", "cobra trading", "choicetrade", "firstrade", "tradezero", "dough", "public", "freetrade", "trading212", "etoro", "plus500", "ig", "city index", "cmc markets", "saxo bank", "swissquote", "degiro", "lynx", "captrader", "banx", "xtb", "xm", "fxcm", "oanda", "forex.com", "pepperstone", "ic markets", "fp markets", "tickmill", "admiral markets", "fxpro", "avatrade", "plus500", "markets.com", "xtrade", "24option", "iqoption", "olymptrade", "binomo", "pocket option", "quotex", "deriv", "binary.com", "nadex", "cantor exchange"],
    
    "Shopping": ["amazon", "ebay", "walmart", "target", "bestbuy", "costco", "homedepot", "lowes", "macys", "nordstrom", "kohls", "jcpenney", "sears", "dillards", "bloomingdales", "neiman marcus", "saks", "barneys", "bergdorf goodman", "lord & taylor", "belk", "boscovs", "von maur", "stage stores", "bealls", "peebles", "goody's", "palais royal", "stage", "gordmans", "shopko", "kmart", "sears", "jcpenney", "mervyns", "gottschalks", "filenes", "kaufmanns", "famous-barr", "foley's", "robinsons-may", "meier & frank", "marshall field's", "hecht's", "strawbridge's", "burdines", "rich's", "lazarus", "goldsmith's", "parisian", "younkers", "carson pirie scott", "bon-ton", "elder-beerman", "herberger's", "boston store", "bergner's", "carson's", "etsy", "poshmark", "mercari", "depop", "vinted", "thredup", "tradesy", "vestiaire collective", "rebag", "fashionphile", "the realreal", "grailed", "stockx", "goat", "stadium goods", "flight club", "kixify", "sneakersnstuff", "end", "size?", "footlocker", "champs", "footaction", "eastbay", "finish line", "jd sports", "snipes", "shiekh", "shoe palace", "villa", "jimmy jazz", "dtlr", "shoe city", "rack room shoes", "famous footwear", "dsw", "payless", "shoe carnival", "shoe show", "shoe dept", "shoe station", "shoe warehouse", "shoe zone", "shoe express", "shoe gallery", "shoe palace", "shoe city", "shoe carnival", "shoe show", "shoe dept", "shoe station", "shoe warehouse", "shoe zone", "shoe express", "shoe gallery"],
    
    "Food": ["doordash", "ubereats", "grubhub", "postmates", "seamless", "caviar", "eat24", "delivery.com", "foodler", "munchery", "sprig", "maple", "chef'd", "blue apron", "hellofresh", "plated", "sun basket", "green chef", "purple carrot", "freshly", "factor", "snap kitchen", "territory foods", "trifecta", "pete's paleo", "paleo on the go", "caveman chefs", "paleorobbie", "paleo power meals", "eatology", "clean eatz", "clean kitchen", "clean plates", "clean simple eats", "clean food crush", "clean eating", "clean eats", "clean meals", "clean food", "clean kitchen", "clean plates", "clean simple eats", "clean food crush", "clean eating", "clean eats", "clean meals", "clean food", "mcdonalds", "burgerking", "wendys", "tacobell", "kfc", "subway", "chickfila", "popeyes", "arbys", "sonic", "jackinthebox", "carlsjr", "hardees", "whitecastle", "fiveguys", "shakeshack", "innout", "culvers", "whataburger", "raising canes", "zaxbys", "bojangles", "churchs", "pollo tropical", "el pollo loco", "del taco", "qdoba", "chipotle", "moes", "baja fresh", "rubios", "chronic tacos", "taco johns", "taco time", "taco cabana", "taco bueno", "taco villa", "taco casa", "taco tico", "taco maker", "taco bell", "taco johns", "taco time", "taco cabana", "taco bueno", "taco villa", "taco casa", "taco tico", "taco maker"],
    
    "Gaming": ["steam", "epicgames", "origin", "uplay", "battlenet", "gog", "humblebundle", "greenmangaming", "g2a", "kinguin", "cdkeys", "gamivo", "eneba", "instant-gaming", "fanatical", "chrono.gg", "indiegala", "bundlestars", "groupees", "itch.io", "gamejolt", "kongregate", "armor games", "newgrounds", "miniclip", "addicting games", "y8", "pogo", "big fish games", "wildtangent", "shockwave", "iwin", "gamehouse", "playfirst", "reflexive", "mumbo jumbo", "sandlot games", "awem", "alawar", "enkord", "game mill", "legacy games", "valusoft", "encore", "viva media", "meridian4", "iceberg interactive", "1c company", "akella", "buka", "snowball", "cenega", "cd projekt", "techland", "ci games", "11 bit studios", "the farm 51", "flying wild hog", "bloober team", "artifex mundi", "juggler games", "forever entertainment", "playway", "gaming company", "all in! games", "movie games", "ultimate games", "gaming factory", "fat dog games", "console classics", "pqube", "merge games", "team17", "rebellion", "codemasters", "frontier", "creative assembly", "sports interactive", "amplitude studios", "relic", "sega", "atlus", "platinum games", "vanillaware", "arc system works", "spike chunsoft", "koei tecmo", "gust", "omega force", "team ninja", "nintendo", "game freak", "hal laboratory", "intelligent systems", "retro studios", "monolith soft", "next level games", "1-up studio", "nd cube", "good-feel", "skip ltd", "creatures inc", "genius sonority", "ambrella", "chunsoft", "spike", "red entertainment", "sting", "idea factory", "compile heart", "gust", "imageepoch", "media.vision", "flight-plan", "neverland", "career soft", "success", "atlus", "vanillaware", "arc system works", "spike chunsoft"],
    
    "Crypto": ["coinbase", "binance", "kraken", "gemini", "bitstamp", "bitfinex", "bittrex", "poloniex", "huobi", "okex", "kucoin", "gate.io", "crypto.com", "ftx", "bybit", "deribit", "bitmex", "phemex", "primexbt", "bitget", "mexc", "ascendex", "probit", "lbank", "bitmart", "hotbit", "xt.com", "digifinex", "coinsbit", "exmo", "cex.io", "coinmama", "blockchain", "exodus", "trust wallet", "metamask", "ledger", "trezor", "keepkey", "coldcard", "bitbox", "opendime", "casa", "unchained capital", "blockfi", "celsius", "nexo", "crypto.com", "youhodler", "hodlnaut", "ledn", "salt", "ethlend", "aave", "compound", "maker", "dharma", "fulcrum", "dydx", "nuo", "bzx", "torque", "ddex", "uniswap", "sushiswap", "pancakeswap", "1inch", "curve", "balancer", "bancor", "kyber", "0x", "airswap", "loopring", "idex", "etherdelta", "forkdelta", "radar relay", "paradex", "dex.ag", "dex.blue", "tokenlon", "dex.top", "switcheo", "nash", "binance dex", "bitshares", "waves dex", "stellar dex", "ripple", "xrp", "stellar", "xlm", "cardano", "ada", "polkadot", "dot", "chainlink", "link", "litecoin", "ltc", "bitcoin cash", "bch", "ethereum classic", "etc", "zcash", "zec", "dash", "monero", "xmr", "tezos", "xtz", "cosmos", "atom", "algorand", "algo", "vechain", "vet", "theta", "tfuel", "elrond", "egld", "filecoin", "fil", "tron", "trx", "eos", "neo", "iota", "miota", "ontology", "ont", "qtum", "icon", "icx", "zilliqa", "zil", "decred", "dcr", "nano", "xno", "digibyte", "dgb", "ravencoin", "rvn", "horizen", "zen", "komodo", "kmd", "waves", "lisk", "lsk", "stratis", "strat", "ark", "pivx", "vertcoin", "vtc", "groestlcoin", "grs", "viacoin", "via", "syscoin", "sys", "namecoin", "nmc", "peercoin", "ppc", "primecoin", "xpm", "feathercoin", "ftc", "novacoin", "nvc", "terracoin", "trc", "megacoin", "mec", "worldcoin", "wdc", "quarkcoin", "qrk", "infinitecoin", "ifc", "ixcoin", "ixc", "devcoin", "dvc", "freicoin", "frc", "i0coin", "i0c", "geistgeld", "gst", "fairbrix", "fbx", "tenebrix", "tbx", "bbqcoin", "bqc", "liquidcoin", "lqc", "solidcoin", "sc", "groupcoin", "grp", "coiledcoin", "clc", "iocoins", "ioc", "fairquark", "fqu", "spots", "spt", "bytecoin", "bcn", "auroracoin", "aur", "mazacoin", "mzc", "einsteinium", "emc2", "unobtanium", "uno", "hobonickels", "hbn", "bottlecaps", "cap", "craftcoin", "crc", "anoncoin", "anc", "zerocoin", "zec", "darkcoin", "drk", "hirocoin", "hiro", "asiccoin", "asc", "dimecoin", "dime", "tagcoin", "tag", "netcoin", "net", "earthcoin", "eac", "redcoin", "red", "flappycoin", "flap", "nyancoin", "nyan", "kittehcoin", "meow", "reddcoin", "rdd", "dogecoin", "doge", "potcoin", "pot", "cannabiscoin", "cann", "dopecoin", "dope", "hempcoin", "thc", "ganjacoin", "mrja", "bongger", "bgr"]
}

# Load services
with open('services_cache.json', 'r') as f:
    all_services = json.load(f)

# Categorize
categorized = {}
uncategorized = []

for service in all_services:
    found = False
    for category, keywords in categories.items():
        if service.lower() in keywords:
            if category not in categorized:
                categorized[category] = []
            categorized[category].append(service)
            found = True
            break
    if not found:
        uncategorized.append(service)

# Save
result = {
    "categories": categorized,
    "uncategorized": uncategorized,
    "pricing": {
        "categorized": 0.50,
        "uncategorized": 0.75
    }
}

with open('services_categorized.json', 'w') as f:
    json.dump(result, f, indent=2)

print(f"✅ Categorized {sum(len(v) for v in categorized.values())} services")
print(f"📦 Uncategorized: {len(uncategorized)} services")
for cat, services in categorized.items():
    print(f"  {cat}: {len(services)} services")
