services:
  - type: web
    name: namaskah-sms
    env: python
    buildCommand: pip install -r requirements.txt && alembic upgrade head && python render_setup.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY  
        generateValue: true
