openapi: 3.0.3
info:
  title: Namaskah SMS API v2
  description: Enhanced SMS verification API with improved rate limiting and error handling
  version: 2.0.0
  contact:
    name: Namaskah Support
    email: support@namaskah.app
    url: https://namaskah.app

servers:
  - url: https://namaskah.app/api/v2
    description: Production server
  - url: http://localhost:8000/api/v2
    description: Development server

security:
  - BearerAuth: []

paths:
  /verify:
    post:
      summary: Create SMS/Voice Verification
      description: Create a new verification with enhanced options and delivery estimates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerificationRequest'
      responses:
        '200':
          description: Verification created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResponse'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '402':
          description: Insufficient credits
        '429':
          description: Rate limit exceeded
          headers:
            X-RateLimit-Limit:
              schema:
                type: integer
            X-RateLimit-Remaining:
              schema:
                type: integer
            X-RateLimit-Reset:
              schema:
                type: integer
            Retry-After:
              schema:
                type: integer

  /verify/{verification_id}:
    get:
      summary: Get Verification Status
      description: Retrieve verification details with enhanced status information
      parameters:
        - name: verification_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Verification details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationDetails'

  /account/usage:
    get:
      summary: Get Usage Statistics
      description: Retrieve detailed usage statistics and rate limit information
      responses:
        '200':
          description: Usage statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageStats'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    VerificationRequest:
      type: object
      required:
        - service_name
      properties:
        service_name:
          type: string
          description: Service identifier (e.g., 'whatsapp', 'telegram')
          example: whatsapp
        capability:
          type: string
          enum: [sms, voice]
          default: sms
          description: Verification method
        webhook_url:
          type: string
          format: uri
          description: Optional webhook URL for notifications
        priority:
          type: boolean
          default: false
          description: Priority processing (premium feature)

    VerificationResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique verification ID
        phone_number:
          type: string
          description: Assigned phone number
        status:
          type: string
          enum: [pending, completed, failed, cancelled]
        cost:
          type: number
          format: float
          description: Cost in Namaskah credits
        estimated_delivery:
          type: integer
          description: Estimated delivery time in seconds

    VerificationDetails:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        phone_number:
          type: string
        messages:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        delivery_attempts:
          type: integer

    UsageStats:
      type: object
      properties:
        current_period:
          type: object
          properties:
            requests:
              type: integer
            limit:
              type: integer
            reset_at:
              type: integer
        monthly_usage:
          type: object
          properties:
            verifications:
              type: integer
            success_rate:
              type: number
            avg_delivery_time:
              type: integer