name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install flake8
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install bandit safety
      - run: bandit -r . -ll || true
      - run: pip install -r requirements.txt && safety check || true

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-test.txt
      - run: python -m pytest tests/ -v --cov=. --cov-report=xml || echo "Tests skipped"
      - uses: codecov/codecov-action@v3
        if: always()

  deploy:
    needs: [lint, security, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy notification
        run: |
          echo "✅ Deployed commit ${{ github.sha }}"
          echo "📦 Branch: ${{ github.ref_name }}"
          echo "👤 Author: ${{ github.actor }}"
