name: Health Check

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Production Health
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://namaskah.app/health)
        if [ $response -ne 200 ]; then
          echo "Health check failed with status $response"
          exit 1
        fi
        echo "Health check passed"
    
    - name: Notify on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: '🚨 Production health check failed!'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
